# -*- coding: utf-8 -*-
"""
Created on 2021-03-19 21:48:07
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class LagouJobListItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i lagou_job_list.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None  # 自增id
        self.job_name = None  # 职位名称
        self.company = None  # 公司
        self.salary = None  # 薪资
        self.job_url = None  # 职位地址
