# -*- coding: utf-8 -*-
"""
Created on 2021-03-19 21:48:13
---------
@summary:
---------
@author: liubo
"""

from feapder import Item


class LagouJobDetailTaskItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i lagou_job_detail_task.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.url = None
        # self.state = 0  # 任务状态（0未做，1完成，2正在做，-1失败）
