# -*- coding: utf-8 -*-
"""
Created on 2021-04-12 16:15:29
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class ZxJournalDetailItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i zx_journal_detail.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.url = None
        self.db_code = None
        self.filename = None
        self.tablename = None
        self.author = None
        self.company = None
        self.task_id = None
