# -*- coding: utf-8 -*-
"""
Created on 2021-07-15 21:10:19
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class BaiduDetailItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i baidu_detail.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.html = None
