# -*- coding: utf-8 -*-
"""
Created on 2021-07-15 21:07:42
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class BaiduListItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i baidu_list.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.url = None
