# -*- coding: utf-8 -*-
"""
Created on 2021-08-29 14:46:26
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class MaoyanCityItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i maoyan_city.
    """

    def __init__(self, *args, **kwargs):
        self.id = None
        self.city_name = None
        self.city_id = None
