# -*- coding: utf-8 -*-
"""
Created on 2021-08-29 15:58:40
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class MaoyanFilmDetailSnapshotTaskItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i maoyan_film_detail_snapshot_task.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.movie_id = None  # 电影id
        self.city_id = None  # 城市id
        self.url = None  # 售票地址
        self.show_time = None  # 播出时间
        self.crawl_time = None  # 采集时间
        # self.state = 0  # 采集状态 -1失败 0 待抓取 1抓取成功 2 正在抓取
