# -*- coding: utf-8 -*-
"""
Created on 2022-12-03 17:29:56
---------
@summary:
---------
@author: boris
"""

from feapder import Item


class MaoyanHotMovieListTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i maoyan_hot_movie_list_task
    """

    __table_name__ = "maoyan_hot_movie_list_task"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.city_id = None
        # self.state = 0  # 采集状态 -1失败 0 待抓取 1抓取成功 2 正在抓取
