# -*- coding: utf-8 -*-
"""
Created on 2021-08-29 16:08:27
---------
@summary:
---------
@author: Boris
"""

from feapder import Item, UpdateItem


class MaoyanFilmDetailItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i maoyan_film_detail.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.movie_id = None  # 电影id
        self.movie_name = None  # 电影名
        self.cinema_id = None  # 影院id
        self.cinema_name = None  # 影院名称
        self.screen = None  # 影厅
        self.version = None  # 版本
        self.show_time = None  # 场次
        self.price = None  # 票价
        self.seat_sold_count = None  # 已售座位
        self.seat_total_count = None  # 总座位
        self.city_id = None  # 城市id
        self.url = None  # 详情地址
        self.crawl_time = None  # 采集时间
        self.update_time = None  # 更新时间


class MaoyanFilmDetailUpdateItem(UpdateItem):
    __table_name__ = "maoyan_film_detail"
    __update_key__ = ["seat_sold_count", "seat_total_count", "update_time"]

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.movie_id = None  # 电影id
        self.movie_name = None  # 电影名
        self.cinema_id = None  # 影院id
        self.cinema_name = None  # 影院名称
        self.screen = None  # 影厅
        self.version = None  # 版本
        self.show_time = None  # 场次
        self.price = None  # 票价
        self.seat_sold_count = None  # 已售座位
        self.seat_total_count = None  # 总座位
        self.city_id = None  # 城市id
        self.url = None  # 详情地址
        self.crawl_time = None  # 采集时间
        self.update_time = None  # 更新时间
