# -*- coding: utf-8 -*-
"""
Created on 2021-08-28 19:25:31
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class MaoyanHotMovieListItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i maoyan_hot_movie_list.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.name = None
        self.movie_id = None  # 电影id
        self.url = None
        self.score = None
        self.cover = None  # 封面
        self.movie_type = None  # 电影类型
        self.main_actor = None  # 主演
        self.release_date = None  # 上映时间
        self.imax = None  # 影片 2d 3d
        self.crawl_time = None  # 采集时间
        self.city_id = None  # 城市id
