# -*- coding: utf-8 -*-
"""
Created on 2021-08-28 20:45:09
---------
@summary:
---------
@author: Boris
"""

from feapder import Item


class MaoyanCinemaListItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i maoyan_cinema_list.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.cinema_id = None
        self.name = None
        self.address = None
        self.tags = None
        self.city_id = None
        self.crawl_time = None
